// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emhjavmbeldztfwbylcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtaGphdm1iZWxkenRmd2J5bGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMDkwMDcsImV4cCI6MjA4NDU4NTAwN30.Z3XvGwXE9qktBbYaJ0lCKyibJHX1RrMruSptlhN01mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});